name: Maven build and deploy

on: [push]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: docker:dind

    services:
      # Label used to access the service container
      tomcat:
        # Docker Hub image
        image: tomcat:9.0
        env:
         name: something
#       docker:
#         # Docker dind image
#         image: docker:dind
        
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          maven-version: 3.5.4

      # Setup JDK in container
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      #Build with Maven 3
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.1
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      
        
      # Testing docker commands
      - name: testing
        run: NAME=`docker ps --filter ancestor=ubuntu --format "{{.Names}}"`
      - name: testing2
        run: echo $NAME
      - name: Copy file
        run: docker cp target/*.war $NAME:/usr/local/tomcat/webapps
