name: Maven build and deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
#     container: docker:dind

    services:
      # Label used to access the service container
      tomcat:
        # Docker Hub image
        image: tomcat:9.0
#       docker:
#         # Docker dind image
#         image: docker:dind
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      
      #Build with Maven 3
#       - name: Setup Maven
#         uses: stCarolas/setup-maven@v4.1
#         with:
#           maven-version: 3.5.4
#       - name: Build with Maven
#         run: mvn --batch-mode --update-snapshots verify
      
        
      # Testing docker commands
      - name: testing
        run: docker ps --filter ancestor=tomcat:9.0 --format "{{.Names}}"
      - name: testing2
        run: echo $NAME
#       - name: Copy file
#         run: docker cp target/*.war $NAME:/usr/local/tomcat/webapps
