name: Maven build and deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    services:
      # Label used to access the service container
      tomcat:
        # Docker Hub image
        image: tomcat:9.0
        
    steps:
    
      # Build Steps  
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}    
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
        
      # Deploying to Tomcat Docker Container
      - name: Getting container name
        run: echo "NAME=`docker ps --filter ancestor=tomcat:9.0 --format "{{.Names}}"`" >> $GITHUB_ENV
        
      - name: Copy file into tomcat container webapps directory
        run: docker cp target/TomcatMavenApp-2.0-SNAPSHOT.war ${{ env.NAME }}:/usr/local/tomcat/webapps/tomcat.war
      
      - name: Wait for the war to explode and then curl to see output
        run: sleep 10 && docker exec ${{ env.NAME }} curl -L localhost:8080/tomcat
  
    
