name: Maven build and deploy

on: [push]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: docker:dind

    services:
      # Label used to access the service container
      tomcat:
        # Docker Hub image
        image: tomcat:9.0
        volumes: 
        - /usr/local/tomcat:/usr/local/tomcat
      docker:
        # Docker dind image
        image: docker:dind
        
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup JDK in container
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
#       #Build with Maven 3
#       - name: Build with Maven
#         run: mvn --batch-mode --update-snapshots verify
        
      # Testing docker commands
      - name: testing
        run: docker ps
      - name: testing2
        run: ls -lrth /usr/local/tomcat
